### ISSUE TITLE
Footprints less accurate than they were before.

### ISSUE THREAD

**Issue by adrianbartyczak** [microsoft/USBuildingFootprints#84]
Footprints were accurate in 2019, and the one's in December 2022 are less accurate.

This is what I noticed only for Manhattan. Not sure if it's like this for other areas.

![screenshot](https://user-images.githubusercontent.com/26193935/216778573-f3808bc0-a36b-451e-9e11-0e33af98388b.png)

**Comment by matt-distefano** [comment]
I have also noticed some troubling issues. Specifically in areas I was looking at, like the Pacific Northwest, Bellingham WA. The footprints seem entirely shifted, sometimes by up to 10feet. I surmise this is because the underlying bing maps data might actually be on erroneous, shifted tiles. When I look at the bing maps data for this image: 
![image](https://user-images.githubusercontent.com/108157334/216785108-05981aa0-955a-4706-b78e-0cb5b77c40f1.png) and then pull the lat/long and check on google maps: 
![image](https://user-images.githubusercontent.com/108157334/216785143-4731d8de-2251-4b70-bc47-3e4592da26a9.png)
The pin is wildly shifted

**Comment by adrianbartyczak** [comment]
Actually, I just realized I'm not even sure if those 2019 geofences I'm showing are from this GitHub page. I'm gonna close this issue.

**Comment by sumanttyagi** [comment]
did any one notice there is some shift and rotation error in many of the footprint when overlaid on basemap ?

@adrianbartyczak and @matt-distefano  how did you fix this ?
